Repository 2025-Mogupick/mogupick_BE, pull requests merged in 2025-09, with the labels that each got.

#22 feat : 카테고리 및 필터 구조 및 조회 구현
  src/main/java/subscribenlike/mogupick/category/CategoryController.java
  src/main/java/subscribenlike/mogupick/category/CategoryOptionMappingGraph.java
  src/main/java/subscribenlike/mogupick/category/CategoryService.java
  src/main/java/subscribenlike/mogupick/category/common/sucess/CategorySuccessCode.java
  src/main/java/subscribenlike/mogupick/category/domain/CategoryOption.java
  src/main/java/subscribenlike/mogupick/category/domain/CategoryOptionFilter.java
  src/main/java/subscribenlike/mogupick/category/domain/CategoryOptionType.java
  src/main/java/subscribenlike/mogupick/category/domain/RootCategory.java
  src/main/java/subscribenlike/mogupick/category/domain/SubCategory.java
  src/main/java/subscribenlike/mogupick/category/model/CategoryOptionAndFilterResponse.java
  src/main/java/subscribenlike/mogupick/category/model/CategoryOptionDto.java
  src/main/java/subscribenlike/mogupick/category/model/RootCategoryResponse.java
  src/test/java/subscribenlike/mogupick/category/CategoryControllerTest.java
  src/test/java/subscribenlike/mogupick/category/CategoryOptionMappingGraphTest.java
  src/test/java/subscribenlike/mogupick/category/CategoryServiceTest.java
  src/test/java/subscribenlike/mogupick/support/fixture/CategoryFixture.java
Labels: feat

#29 feat : 상품 저장 및 카테고리별 상품 조회 구현
  build.gradle
  src/main/java/subscribenlike/mogupick/category/CategoryService.java
  src/main/java/subscribenlike/mogupick/product/common/ProductErrorCode.java
  src/main/java/subscribenlike/mogupick/product/common/ProductSuccessCode.java
  src/main/java/subscribenlike/mogupick/product/controller/ProductController.java
  src/main/java/subscribenlike/mogupick/product/domain/Product.java
  src/main/java/subscribenlike/mogupick/product/domain/ProductOption.java
  src/main/java/subscribenlike/mogupick/product/domain/ProductType.java
  src/main/java/subscribenlike/mogupick/product/model/CreateProductRequest.java
  src/main/java/subscribenlike/mogupick/product/model/ProductWithOptionResponse.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductOptionRepository.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductRepository.java
  src/main/java/subscribenlike/mogupick/product/service/ProductService.java
  src/test/java/subscribenlike/mogupick/product/ProductControllerTest.java
  src/test/java/subscribenlike/mogupick/product/ProductOptionFixture.java
  src/test/java/subscribenlike/mogupick/product/ProductServiceTest.java
Labels: feat

#43 fix: Gradle 빌드 오류 해결 및 Member 엔티티 수정
  src/main/java/subscribenlike/mogupick/global/config/JpaConfig.java
  src/main/java/subscribenlike/mogupick/member/domain/Member.java
Labels: fix

#31 feat: 로그아웃 기능 구현 및 로그인 로직 보완
  src/main/java/subscribenlike/mogupick/auth/controller/AuthController.java
  src/main/java/subscribenlike/mogupick/auth/service/AuthService.java
  src/main/java/subscribenlike/mogupick/global/jwt/JwtProvider.java
  src/main/java/subscribenlike/mogupick/global/oauth/OAuth2LoginSuccessHandler.java
  src/main/java/subscribenlike/mogupick/member/repository/MemberRepository.java
Labels: feat

#45 feat: 토큰 재발급(Refresh) 기능 구현
  src/main/java/subscribenlike/mogupick/auth/controller/AuthController.java
  src/main/java/subscribenlike/mogupick/auth/dto/TokenReissueDto.java
  src/main/java/subscribenlike/mogupick/auth/service/AuthService.java
  src/main/java/subscribenlike/mogupick/member/repository/MemberRepository.java
Labels: feat

#44 feat : 내 또래의 베스트 리뷰 조회하기
  src/main/java/subscribenlike/mogupick/member/domain/Member.java
  src/main/java/subscribenlike/mogupick/product/common/ProductSuccessCode.java
  src/main/java/subscribenlike/mogupick/product/controller/ProductController.java
  src/main/java/subscribenlike/mogupick/product/model/FetchPeerBestReviewsResponse.java
  src/main/java/subscribenlike/mogupick/product/model/query/FetchPeerBestReviewsQueryResult.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductRepository.java
  src/main/java/subscribenlike/mogupick/product/service/ProductService.java
  src/main/java/subscribenlike/mogupick/review/domain/ReviewLike.java
  src/main/java/subscribenlike/mogupick/review/repository/ReviewLikeRepository.java
  src/test/java/subscribenlike/mogupick/member/ProductTestMemberFixture.java
  src/test/java/subscribenlike/mogupick/product/ProductControllerTest.java
  src/test/java/subscribenlike/mogupick/product/repository/ProductRepositoryTest.java
  src/test/java/subscribenlike/mogupick/product/service/ProductServiceTest.java
  src/test/java/subscribenlike/mogupick/review/ReviewLikeFixture.java
  src/test/java/subscribenlike/mogupick/support/fixture/BrandFixture.java
  src/test/java/subscribenlike/mogupick/support/fixture/MemberFixture.java
  src/test/java/subscribenlike/mogupick/support/fixture/ProductFixture.java
  src/test/resources/application-test.yml
Labels: feat

#54 fix: SecurityConfig 빈 주입 오류 및 Member 테스트 생성자 추가
  src/main/java/subscribenlike/mogupick/global/config/CorsConfig.java
  src/main/java/subscribenlike/mogupick/member/domain/Member.java
Labels: fix

#48 장바구니 관련 기능 구현
  src/main/java/subscribenlike/mogupick/cart/common/exception/CartErrorCode.java
  src/main/java/subscribenlike/mogupick/cart/common/exception/CartException.java
  src/main/java/subscribenlike/mogupick/cart/common/success/CartSuccessCode.java
  src/main/java/subscribenlike/mogupick/cart/controller/CartController.java
  src/main/java/subscribenlike/mogupick/cart/domain/Cart.java
  src/main/java/subscribenlike/mogupick/cart/domain/CartItem.java
  src/main/java/subscribenlike/mogupick/cart/dto/CartAddRequest.java
  src/main/java/subscribenlike/mogupick/cart/dto/CartItemOptionUpdateRequest.java
  src/main/java/subscribenlike/mogupick/cart/dto/CartItemResponse.java
  src/main/java/subscribenlike/mogupick/cart/dto/CartResponse.java
  src/main/java/subscribenlike/mogupick/cart/repository/CartItemRepository.java
  src/main/java/subscribenlike/mogupick/cart/repository/CartRepository.java
  src/main/java/subscribenlike/mogupick/cart/service/CartService.java
  src/main/java/subscribenlike/mogupick/member/repository/MemberRepository.java
  src/main/java/subscribenlike/mogupick/subscriptionOption/domain/SubscriptionOption.java
  src/main/java/subscribenlike/mogupick/subscriptionOption/domain/SubscriptionPeriodUnit.java
Labels: feat

#50 feat: 내 정보 관리(조회 및 수정) 기능 구현
  build.gradle
  src/main/java/subscribenlike/mogupick/member/controller/MemberController.java
  src/main/java/subscribenlike/mogupick/member/domain/Member.java
  src/main/java/subscribenlike/mogupick/member/dto/MemberResponse.java
  src/main/java/subscribenlike/mogupick/member/dto/MemberUpdateRequest.java
  src/main/java/subscribenlike/mogupick/member/service/MemberService.java
Labels: feat

#68 feat: CustomUserDetails 구현하여 인증 정보에 memberId 추가
  src/main/java/subscribenlike/mogupick/global/jwt/JwtProvider.java
  src/main/java/subscribenlike/mogupick/global/security/CustomUserDetails.java
  src/main/java/subscribenlike/mogupick/member/controller/MemberController.java
Labels: feat

#59 docs: Auth, Member API 스웨거 문서 추가
  src/main/java/subscribenlike/mogupick/auth/controller/AuthController.java
  src/main/java/subscribenlike/mogupick/global/dto/ApiResponse.java
  src/main/java/subscribenlike/mogupick/global/dto/GlobalResponse.java
  src/main/java/subscribenlike/mogupick/member/controller/MemberController.java
Labels: feat

#74 feat : Product, Review 다중 이미지 지원
  src/main/java/subscribenlike/mogupick/common/model/PaginatedResponse.java
  src/main/java/subscribenlike/mogupick/common/utils/S3Service.java
  src/main/java/subscribenlike/mogupick/product/controller/ProductController.java
  src/main/java/subscribenlike/mogupick/product/controller/ProductViewCountController.java
  src/main/java/subscribenlike/mogupick/product/domain/Product.java
  src/main/java/subscribenlike/mogupick/product/domain/ProductMedia.java
  src/main/java/subscribenlike/mogupick/product/model/CreateProductRequest.java
  src/main/java/subscribenlike/mogupick/product/model/FetchPeerBestReviewsResponse.java
  src/main/java/subscribenlike/mogupick/product/model/query/FetchPeerBestReviewsQueryResult.java
  src/main/java/subscribenlike/mogupick/product/model/query/ProductsInMonthQueryResult.java
  src/main/java/subscribenlike/mogupick/product/repository/MemberProductViewCountQuerydslRepositoryImpl.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductMediaRepository.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductQuerydslRepositoryImpl.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductRepository.java
  src/main/java/subscribenlike/mogupick/product/service/ProductService.java
  src/main/java/subscribenlike/mogupick/product/service/ProductViewCountService.java
  src/main/java/subscribenlike/mogupick/review/controller/ReviewController.java
  src/main/java/subscribenlike/mogupick/review/domain/Review.java
  src/main/java/subscribenlike/mogupick/review/domain/ReviewMedia.java
  src/main/java/subscribenlike/mogupick/review/model/CreateReviewRequest.java
  src/main/java/subscribenlike/mogupick/review/repository/ReviewMediaRepository.java
  src/main/java/subscribenlike/mogupick/review/service/ReviewService.java
  src/test/java/subscribenlike/mogupick/product/ProductControllerTest.java
  src/test/java/subscribenlike/mogupick/product/ProductFixture.java
  src/test/java/subscribenlike/mogupick/product/ProductQuerydslRepositoryTest.java
  src/test/java/subscribenlike/mogupick/product/ProductServiceTest.java
  src/test/java/subscribenlike/mogupick/product/ProductViewCountControllerTest.java
  src/test/java/subscribenlike/mogupick/product/ProductViewCountServiceTest.java
  src/test/java/subscribenlike/mogupick/product/repository/ProductRepositoryTest.java
  src/test/java/subscribenlike/mogupick/review/ReviewFixture.java
  src/test/java/subscribenlike/mogupick/review/service/ReviewServiceTest.java
  src/test/java/subscribenlike/mogupick/support/fixture/ProductFixture.java
  src/test/java/subscribenlike/mogupick/support/fixture/ReviewFixture.java
  src/test/resources/application-test.yml
Labels: feat

#77 feat: Toss 결제 연동 및 빌링키 암호화 기능 구현
  build.gradle
  src/main/java/subscribenlike/mogupick/billing/common/exception/BillingErrorCode.java
  src/main/java/subscribenlike/mogupick/billing/common/exception/BillingException.java
  src/main/java/subscribenlike/mogupick/billing/common/exception/CryptoErrorCode.java
  src/main/java/subscribenlike/mogupick/billing/common/exception/CryptoException.java
  src/main/java/subscribenlike/mogupick/billing/common/success/BillingSuccessCode.java
  src/main/java/subscribenlike/mogupick/billing/config/BillingConfig.java
  src/main/java/subscribenlike/mogupick/billing/controller/BillingController.java
  src/main/java/subscribenlike/mogupick/billing/domain/BillingKeyCredential.java
  src/main/java/subscribenlike/mogupick/billing/domain/PaymentState.java
  src/main/java/subscribenlike/mogupick/billing/domain/PaymentStatus.java
  src/main/java/subscribenlike/mogupick/billing/dto/ChargeRequest.java
  src/main/java/subscribenlike/mogupick/billing/dto/FirstChargeRequest.java
  src/main/java/subscribenlike/mogupick/billing/dto/PaymentStateResponse.java
  src/main/java/subscribenlike/mogupick/billing/repository/BillingKeyCredentialRepository.java
  src/main/java/subscribenlike/mogupick/billing/repository/PaymentStateRepository.java
  src/main/java/subscribenlike/mogupick/billing/service/BillingKeyService.java
  src/main/java/subscribenlike/mogupick/billing/service/FirstChargeOrchestrator.java
  src/main/java/subscribenlike/mogupick/billing/service/PaymentService.java
  src/main/java/subscribenlike/mogupick/billing/service/RecurringChargeService.java
  src/main/java/subscribenlike/mogupick/billing/service/client/TossPaymentsClient.java
  src/main/java/subscribenlike/mogupick/billing/util/AesGcm.java
  src/test/java/subscribenlike/mogupick/billing/BillingKeyServiceTest.java
  src/test/java/subscribenlike/mogupick/billing/FirstChargeOrchestratorTest.java
  src/test/java/subscribenlike/mogupick/billing/PaymentServiceTest.java
  src/test/java/subscribenlike/mogupick/billing/RecurringChargeServiceTest.java
  src/test/java/subscribenlike/mogupick/support/fixture/BillingFixture.java
Labels: feat

#91 feat: 결제 예정 알림 스케줄러 구현
  src/main/java/subscribenlike/mogupick/MogupickApplication.java
  src/main/java/subscribenlike/mogupick/notification/domain/Notification.java
  src/main/java/subscribenlike/mogupick/notification/domain/NotificationType.java
  src/main/java/subscribenlike/mogupick/notification/repository/NotificationRepository.java
  src/main/java/subscribenlike/mogupick/notification/scheduler/NotificationScheduler.java
  src/main/java/subscribenlike/mogupick/notification/service/NotificationService.java
  src/main/java/subscribenlike/mogupick/subscription/domain/Subscription.java
  src/main/java/subscribenlike/mogupick/subscription/repository/SubscriptionRepository.java
Labels: feat

#86 feat: 배송지 등록, 수정 ,삭제 기능 구현
  src/main/java/subscribenlike/mogupick/auth/service/AuthService.java
  src/main/java/subscribenlike/mogupick/common/config/S3Config.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/common/exception/DeliveryAddressErrorCode.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/common/exception/DeliveryAddressException.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/common/success/DeliveryAddressSuccessCode.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/controller/DeliveryAddressController.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/domain/DeliveryAddress.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/dto/DeliveryAddressRequest.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/dto/DeliveryAddressResponse.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/dto/DeliveryAddressUpdateRequest.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/repository/DeliveryAddressRepository.java
  src/main/java/subscribenlike/mogupick/deliveryAddress/service/DeliveryAddressService.java
  src/main/java/subscribenlike/mogupick/searchKeyword/dto/SearchProductResponse.java
  src/test/java/subscribenlike/mogupick/deliveryAddress/DeliveryAddressControllerTest.java
  src/test/java/subscribenlike/mogupick/deliveryAddress/DeliveryAddressServiceTest.java
  src/test/java/subscribenlike/mogupick/support/fixture/DeliveryAddressFixture.java
Labels: feat

#100 refactor: member, notification repository 조회 로직 리팩토링
  src/main/java/subscribenlike/mogupick/auth/service/AuthService.java
  src/main/java/subscribenlike/mogupick/member/repository/MemberRepository.java
  src/main/java/subscribenlike/mogupick/member/service/MemberService.java
  src/main/java/subscribenlike/mogupick/notification/repository/NotificationRepository.java
  src/main/java/subscribenlike/mogupick/notification/service/NotificationService.java
Labels: refactor

#98 fix: conflict 해결할 때 발생한 문제 수정
  src/main/java/subscribenlike/mogupick/common/utils/S3Service.java
  src/main/java/subscribenlike/mogupick/notification/scheduler/NotificationScheduler.java
  src/main/java/subscribenlike/mogupick/product/service/ProductService.java
  src/main/java/subscribenlike/mogupick/searchKeyword/dto/SearchProductResponse.java
  src/main/java/subscribenlike/mogupick/subscription/dto/SubscriptionResponse.java
  src/main/java/subscribenlike/mogupick/subscription/repository/SubscriptionRepository.java
Labels: bug

#101 fix : 컴파일 에러 해결 및 코드 수정
  src/main/java/subscribenlike/mogupick/brand/controller/BrandController.java
  src/main/java/subscribenlike/mogupick/common/error/handler/GlobalExceptionHandler.java
  src/main/java/subscribenlike/mogupick/product/service/SimilarProductFetchService.java
  src/main/java/subscribenlike/mogupick/subscription/domain/SubscriptionRepository.java
Labels: fix

#105 fix : 상품 생성을 위한 코드 수정
  .gitignore
  src/main/java/subscribenlike/mogupick/brand/controller/BrandController.java
  src/main/java/subscribenlike/mogupick/category/domain/RootCategory.java
  src/main/java/subscribenlike/mogupick/category/domain/SubCategory.java
  src/main/java/subscribenlike/mogupick/common/utils/S3Service.java
  src/main/java/subscribenlike/mogupick/global/jwt/JwtAuthenticationFilter.java
  src/main/java/subscribenlike/mogupick/product/domain/ProductDescriptionMedia.java
  src/main/java/subscribenlike/mogupick/product/domain/ProductMedia.java
  src/main/java/subscribenlike/mogupick/product/model/CreateProductRequest.java
  src/main/java/subscribenlike/mogupick/review/domain/ReviewMedia.java
Labels: fix

#104 feat: 배송 도메인, 이벤트 알림 구현
  src/main/java/subscribenlike/mogupick/billing/service/PaymentService.java
  src/main/java/subscribenlike/mogupick/delivery/common/exception/DeliveryErrorCode.java
  src/main/java/subscribenlike/mogupick/delivery/common/exception/DeliveryException.java
  src/main/java/subscribenlike/mogupick/delivery/common/success/DeliverySuccessCode.java
  src/main/java/subscribenlike/mogupick/delivery/controller/DeliveryController.java
  src/main/java/subscribenlike/mogupick/delivery/domain/Delivery.java
  src/main/java/subscribenlike/mogupick/delivery/domain/DeliveryStatus.java
  src/main/java/subscribenlike/mogupick/delivery/repository/DeliveryRepository.java
  src/main/java/subscribenlike/mogupick/delivery/service/DeliveryService.java
  src/main/java/subscribenlike/mogupick/global/config/SecurityConfig.java
  src/main/java/subscribenlike/mogupick/notification/domain/NotificationType.java
  src/main/java/subscribenlike/mogupick/notification/scheduler/NotificationScheduler.java
Labels: feat

#109 feat: 기존 소셜 로그인 방식 복구
  src/main/java/subscribenlike/mogupick/global/config/SecurityConfig.java
  src/main/java/subscribenlike/mogupick/global/oauth/CustomOAuth2UserService.java
  src/main/java/subscribenlike/mogupick/global/oauth/OAuth2LoginFailureHandler.java
  src/main/java/subscribenlike/mogupick/global/oauth/OAuth2LoginSuccessHandler.java
Labels: feat

#116 fix: 리다이렉트 URL 변경
  src/main/java/subscribenlike/mogupick/global/oauth/OAuth2LoginSuccessHandler.java
Labels: fix

#121 fix: 사용자의 웹 브라우저에 잠시 쿠키로 저장하는 방식 변경
  src/main/java/subscribenlike/mogupick/auth/controller/AuthController.java
  src/main/java/subscribenlike/mogupick/auth/service/AuthService.java
  src/main/java/subscribenlike/mogupick/common/utils/CookieUtil.java
  src/main/java/subscribenlike/mogupick/global/config/SecurityConfig.java
  src/main/java/subscribenlike/mogupick/global/oauth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/subscribenlike/mogupick/global/oauth/OAuth2LoginFailureHandler.java
  src/main/java/subscribenlike/mogupick/global/oauth/OAuth2LoginSuccessHandler.java
Labels: fix

#123 feat : 응답구조 수정
  src/main/java/subscribenlike/mogupick/category/domain/SubCategory.java
  src/main/java/subscribenlike/mogupick/product/domain/ProductOption.java
  src/main/java/subscribenlike/mogupick/product/model/FetchBeginnerFriendlyProductResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchConstantlyPopularProductResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchNewProductsInMonthResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchProductMostDailyViewStatChangeResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchProductOptionResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchProductWithOptionResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchRecentlyViewProductResponse.java
  src/main/java/subscribenlike/mogupick/product/model/FetchSimilarProductResponse.java
  src/main/java/subscribenlike/mogupick/product/repository/ProductQuerydslRepositoryImpl.java
  src/main/java/subscribenlike/mogupick/product/service/ProductService.java
  src/main/java/subscribenlike/mogupick/product/service/ProductViewCountService.java
  src/main/java/subscribenlike/mogupick/product/service/SimilarProductFetchService.java
Labels: fix
